# Generated by Django 3.2.3 on 2024-04-12 17:11

import uttils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким username или с таким email уже существует'}, help_text='Не больше 150 символов.Только буквы, цифры и @/./+/-/_', max_length=150, unique=True, validators=[uttils.validators.validate_username], verbose_name='Пользователь'),
        ),
    ]
